commands:
  # Time commands
  - command:
    input: What time is?
    entity: time
    action: getTime

  - command:
    input: Tell me the time
    entity: time
    action: getTime
  # Date commands
  - command:
    input: What date is?
    entity: time
    action: getDate
  - command:
    input: Tell me the date.
    entity: time
    action: getDate
  # Year command
  - command:
    input: Tell me which year is
    entity: time
    action: getYear
  - command:
    input: Which year is it?
    entity: time
    action: getYear
  # Weather
  - command:
    input: What's the weather?
    entity: time
    action: getWeather
  - command:
    input: What's the weather like?
    entity: time
    action: getWeather
  # Open
  - command:
    input: Open Google
    entity: open
    action: google

