# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'faqMyzCHz.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1084, 913)
        self.widget = QWidget(Form)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 50, 771, 861))
        self.widget.setStyleSheet(u"background-color: #2b3038;\n"
"border-radius: 30px;")
        self.exitButton = QPushButton(self.widget)
        self.exitButton.setObjectName(u"exitButton")
        self.exitButton.setGeometry(QRect(700, 10, 41, 41))
        self.exitButton.setStyleSheet(u"QPushButton{\n"
"background-color: #20242a;\n"
"color: #20242a;\n"
"border-radius: 50px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"}")
        icon = QIcon()
        icon.addFile(u"../../icons/x_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QSize(30, 30))
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 80, 71, 41))
        font = QFont()
        font.setFamily(u"Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 120, 101, 41))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 160, 51, 41))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 200, 51, 41))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 240, 51, 41))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_6 = QLabel(self.widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 280, 51, 41))
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 320, 131, 41))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 360, 91, 41))
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 400, 121, 41))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_10 = QLabel(self.widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 440, 101, 41))
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_11 = QLabel(self.widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 480, 71, 41))
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_12 = QLabel(self.widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 520, 51, 41))
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_13 = QLabel(self.widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 560, 51, 41))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_14 = QLabel(self.widget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(30, 600, 61, 41))
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_15 = QLabel(self.widget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 640, 101, 41))
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_16 = QLabel(self.widget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 680, 71, 41))
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_17 = QLabel(self.widget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 720, 91, 41))
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_18 = QLabel(self.widget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 760, 181, 41))
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_19 = QLabel(self.widget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 800, 111, 41))
        self.label_19.setFont(font)
        self.label_19.setStyleSheet(u"color: rgb(5, 109, 0);")
        self.label_20 = QLabel(self.widget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(100, 80, 201, 41))
        self.label_20.setFont(font)
        self.label_20.setStyleSheet(u"color: rgb(38, 0, 255);")
        self.label_21 = QLabel(self.widget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(140, 120, 151, 41))
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(u"color: rgb(38, 0, 255);")
        self.label_22 = QLabel(self.widget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(90, 160, 131, 41))
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(u"color: rgb(38, 0, 255);")
        self.label_23 = QLabel(self.widget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(100, 240, 111, 41))
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(u"color: rgb(38, 0, 255);")
        self.label_24 = QLabel(self.widget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(100, 280, 131, 41))
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(u"color: rgb(38, 0, 255);")
        self.label_25 = QLabel(self.widget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(130, 360, 51, 41))
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(u"color: rgb(38, 0, 255);")
        self.label_26 = QLabel(self.widget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(190, 360, 111, 41))
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(u"color: rgb(49, 200, 255);\n"
"")
        self.label_27 = QLabel(self.widget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(210, 760, 191, 41))
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(u"color: rgb(38, 0, 255);")
        self.label_28 = QLabel(self.widget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(320, 80, 411, 41))
        font1 = QFont()
        font1.setFamily(u"Segoe UI")
        font1.setPointSize(11)
        self.label_28.setFont(font1)
        self.label_28.setStyleSheet(u"color: #837c73;\n"
"")
        self.label_29 = QLabel(self.widget)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(320, 120, 421, 41))
        self.label_29.setFont(font1)
        self.label_29.setStyleSheet(u"color: #837c73;\n"
"")
        self.label_30 = QLabel(self.widget)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(240, 160, 411, 41))
        self.label_30.setFont(font1)
        self.label_30.setStyleSheet(u"color: #837c73;\n"
"")
        self.label_31 = QLabel(self.widget)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(250, 280, 331, 41))
        self.label_31.setFont(font1)
        self.label_31.setStyleSheet(u"color: #837c73;\n"
"")
        self.label_32 = QLabel(self.widget)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(320, 360, 441, 41))
        font2 = QFont()
        font2.setFamily(u"Segoe UI")
        font2.setPointSize(9)
        self.label_32.setFont(font2)
        self.label_32.setStyleSheet(u"color: #837c73;\n"
"")
        self.label_33 = QLabel(self.widget)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(90, 560, 251, 41))
        self.label_33.setFont(font1)
        self.label_33.setStyleSheet(u"color: #837c73;\n"
"")
        self.label_34 = QLabel(self.widget)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(110, 600, 141, 41))
        self.label_34.setFont(font1)
        self.label_34.setStyleSheet(u"color: #837c73;\n"
"")

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.exitButton.setText("")
        self.label.setText(QCoreApplication.translate("Form", u"open", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"wikipedia", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"play", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"date", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"news", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"note", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"make a note", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"weather", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"send email", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"send sms", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"notify", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"help", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"joke", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"game", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"calculate", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"spotify", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"flip coin", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"search in google", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"thank you", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"[application name]", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"[person name]", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"[song name]", None))
        self.label_23.setText("")
        self.label_24.setText(QCoreApplication.translate("Form", u"[text of note]", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"[city]", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"OPTIONAL", None))
        self.label_27.setText(QCoreApplication.translate("Form", u"[phrase in Google]", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"- opening an application specified by user", None))
        self.label_29.setText(QCoreApplication.translate("Form", u"- information about subject specified by user", None))
        self.label_30.setText(QCoreApplication.translate("Form", u"- starting YouTube video", None))
        self.label_31.setText(QCoreApplication.translate("Form", u"- saves a note with text specified by user", None))
        self.label_32.setText(QCoreApplication.translate("Form", u"- information about weather in current location or specified city", None))
        self.label_33.setText(QCoreApplication.translate("Form", u"- random joke from assistant", None))
        self.label_34.setText(QCoreApplication.translate("Form", u"- coin toss game", None))
    # retranslateUi

